### ISSUE TITLE
Cannot start runner with pool file

### ISSUE THREAD

**Issue by webfrank** [drone-runners/drone-runner-aws#359]
Hi,
  was trying to start an AWS runner with a pool.yaml file but I have this error:

```
drone_aws.1.v3aytmcmyklk@docker02    | time="2023-09-29T15:15:03Z" level=info msg="Loading pool file '/config/pool.yaml'"
drone_aws.1.v3aytmcmyklk@docker02    | time="2023-09-29T15:15:03Z" level=error msg="exec: unable to parse pool file" error="json: cannot unmarshal array into Go struct field PoolFile.instances of type map[string]string" path=/config/pool.yaml
drone_aws.1.v3aytmcmyklk@docker02    | time="2023-09-29T15:15:03Z" level=fatal msg="daemon: unable to load pool file, or use an in memory pool file" error="json: cannot unmarshal array into Go struct field PoolFile.instances of type map[string]string"
```

The pool.yaml file is:
```
version: "1"

instances:
- name: gpu
  default: true
  type: amazon
  pool: 0    # total number of warm instances in the pool at all times
  limit: 1   # limit the total number of running servers. If exceeded block or error.
  platform:
    os: linux
    arch: amd64
  spec:
    account:
      region: eu-west-1
      access_key_id: xxx
      access_key_secret: xxx
    ami: ami-0f9aaa549abd8f082
    size: g4dn.2xlarge
    tags:
    - Training
```
