### ISSUE TITLE
Azure drivwer is not working correctly, when it tries to execute more than one job in parallel

### ISSUE THREAD

**Issue by Ben10k** [drone-runners/drone-runner-aws#384]
I am using the latest versions of:
* self-hsoted Drone ( [2.20.0](https://github.com/harness/gitness/releases/tag/v2.20.0) )
* drone-runner-aws ( [v1.0.0-rc.105](https://github.com/drone-runners/drone-runner-aws/releases/tag/v1.0.0-rc.105) )

`.drone_pool.yml` that works:
```yaml
version: "1"
instances:
- name: ubuntu-azure
  default: true
  type: azure
  pool: 0
  limit: 1
  platform:
    os: linux
    arch: amd64
  spec:
    account:
      client_id: "****"
      client_secret: "****"
      subscription_id: "****"
      tenant_id: "****"
    resource_group: drone-runners
    location: eastus2
    size: Standard_B4s_v2
    image:
      username: "****"
      password: "****"
      publisher: canonical
      offer: 0001-com-ubuntu-server-focal
      sku: 20_04-lts-gen2
      version: latest
```
When I try to run pipelines, this configuration works, but if I increase the `limit` to anything above and try to run parallel pipleines, something stops working.
* Both pipeline stages turn yellow and the timer starts.
* In the azure portal and runner's logs I can see that 2 VMs are provisioned
* After about 60-80 seconds, one job starts running, and work as expected, when the pipeline finishes, the VM gets destroyed (visible both in runner's logs and on Azure portal)
* Another job stays in progress, but steps do not start
* After about 20-21 minutes, the pipeline stage fails with `context deadline exceeded`
* After enabling the trace and debug logs on the runner, I found these log messages, which indicate that if a few VMs are started at the same time, the runner assigns the same IP addresses for VMs
```
time="2023-12-02T11:36:06Z" level=debug msg="azure: [provision] complete" cloud=azure fields.time=47.23s image=0001-com-ubuntu-server-focal ip=20.230.100.19 name=drone-runner-vm-cd8fb7c9b-6gn44-ubuntu-azure-XWp05980 pool=ubuntu-azure size=Standard_B4s_v2 zone="[]"
time="2023-12-02T11:36:08Z" level=debug msg="azure: [provision] complete" cloud=azure fields.time=48.40s image=0001-com-ubuntu-server-focal ip=20.230.100.19 name=drone-runner-vm-cd8fb7c9b-6gn44-ubuntu-azure-basMfX91 pool=ubuntu-azure size=Standard_B4s_v2 zone="[]"
time="2023-12-02T11:36:09Z" level=debug msg="azure: [provision] complete" cloud=azure fields.time=47.53s image=0001-com-ubuntu-server-focal ip=20.230.100.19 name=drone-runner-vm-cd8fb7c9b-6gn44-ubuntu-azure-5v88gnFS pool=ubuntu-azure size=Standard_B4s_v2 zone="[]"

```

If I increase the `pool` value to anything more than 0, than all pipelines timeout with the same issues.

Note: I have tried the same runner with the same pipelines with another pool of AWS instances and it worked perfectly.
